ncsudo: required
language: python
python:
- 3.7
- 3.6

install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: stevenmi
  password:
    secure: x5GeBV3blmcHSuWE9dt4iKt1+/L79CuwI4T39C3Y94q/SH4xoAklhXjfP7i2VfFeLhN1s1zeqrCvXq74bWBkeJePWqBBatIwQ3X7UGe/fXssty0qHEtquQIwaQu09ny3Zuh/P7tCL/B7zAKzjEhwubQWu3fuQj00vuNRkrkfLh5O8chIb38wf96RQlF3RaRWF6xUikvICJheuQnlup5jwAGipB01R3dANe0PnpXehRxR2Y8n28w9FP+bbKSdAq5/JVpNPWy3xDl62lv451vEaDgYONIjv93Kjq0lrC7Ei0l+M5DXyVf+Q3Heag8qKY+s4g9xQ/6KxfcXK0XpLQp3a6Rp7Ek1XaALK3jXKg9os/WOwIUIvCiMY739cowPPvUWgDTirPoHKXkFOc0wTmaz9Om9vWX6X4jUJN7c7I0+wllgdFv0BEMzNR6eouI91o9ZlBv3vdWQHD4s8sSpyduKyJRXOQoFPPvuTMDUTCtFgttMpG7z7ocWg8uGoSa0v2lxCYQ1RGzzB/dtsTAiFOQiyQ3e42gWfXmbe65QqEIp0eirgM1ByQLC+tEH2NVHa0/uVbdQGfsdg9GagdoWT0SmCVLao2FtY7hhktoM4vnjgfRt+momTsKT0H7A/TfnOnYUfjAnLcAj4Myuw8wKs9NSZZoUs/zp4fv1h2O0Je7umc8=
  on:
    all_branches: true
  distributions: sdist bdist_wheel
  skip_existing: true
